// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFQtYU-VRFJnk-GRVwVozn597JK3BS-o',
    appId: '1:591679405583:web:67cd7c566ad8b96db6ad7a',
    messagingSenderId: '591679405583',
    projectId: 'clinic-booking-system-18e7d',
    authDomain: 'clinic-booking-system-18e7d.firebaseapp.com',
    storageBucket: 'clinic-booking-system-18e7d.firebasestorage.app',
    measurementId: 'G-FD4Q9SZP6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_D5kwdkJIXWREi28C1OUA5QTFDreXaE',
    appId: '1:591679405583:android:a0572ffb296c9fc7b6ad7a',
    messagingSenderId: '591679405583',
    projectId: 'clinic-booking-system-18e7d',
    storageBucket: 'clinic-booking-system-18e7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqERTMCN1syMnVHWfi1jdAH4zi4CZeQwE',
    appId: '1:591679405583:ios:3093627b8643e899b6ad7a',
    messagingSenderId: '591679405583',
    projectId: 'clinic-booking-system-18e7d',
    storageBucket: 'clinic-booking-system-18e7d.firebasestorage.app',
    iosBundleId: 'com.example.clinicBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqERTMCN1syMnVHWfi1jdAH4zi4CZeQwE',
    appId: '1:591679405583:ios:3093627b8643e899b6ad7a',
    messagingSenderId: '591679405583',
    projectId: 'clinic-booking-system-18e7d',
    storageBucket: 'clinic-booking-system-18e7d.firebasestorage.app',
    iosBundleId: 'com.example.clinicBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeFQtYU-VRFJnk-GRVwVozn597JK3BS-o',
    appId: '1:591679405583:web:7b4e2c441dcb31b6b6ad7a',
    messagingSenderId: '591679405583',
    projectId: 'clinic-booking-system-18e7d',
    authDomain: 'clinic-booking-system-18e7d.firebaseapp.com',
    storageBucket: 'clinic-booking-system-18e7d.firebasestorage.app',
    measurementId: 'G-35EH3VF2W0',
  );
}
