name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/backend-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clinic-be:latest

      # Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Web
          file: ./Web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clinic-fe:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy file docker-compose.yml to server
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/app/"

      # SSH into server và run command deploy
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/app

            # Tạo file .env từ secrets để docker-compose đọc
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env

            # Pull image mới nhất về
            docker compose pull

            # Restart containers (chỉ update những cái thay đổi)
            docker compose up -d --remove-orphans

            # Dọn dẹp image cũ cho đỡ tốn dung lượng
            docker image prune -f
